/*
 * MCPX APU MMIO Hook - VEH instruction decoder for APU register access
 *
 * Reuses the same x86-64 instruction decoder pattern as nv2a_mmio_hook.c
 * but routes reads/writes through the MCPX APU register handlers.
 */

#include "apu.h"
#include <windows.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

/* APU MMIO base in Xbox VA space */
#define APU_MMIO_BASE  0xFE800000u
#define APU_MMIO_SIZE  0x00080000u  /* 512KB */

/* Global APU state */
MCPXAPUState *g_apu_state = NULL;

/* Statistics */
int g_apu_mmio_read_count = 0;     /* non-static: read by apu_debug_stats_line */
int g_apu_mmio_write_count = 0;
int g_apu_mmio_decode_fail = 0;
static int g_apu_mmio_sse_count = 0;

/* ============================================================
 * x86-64 register access helpers (same as NV2A hook)
 * ============================================================ */

static uint64_t *ctx_reg64(PCONTEXT ctx, int reg)
{
    switch (reg & 0xF) {
    case 0:  return (uint64_t*)&ctx->Rax;
    case 1:  return (uint64_t*)&ctx->Rcx;
    case 2:  return (uint64_t*)&ctx->Rdx;
    case 3:  return (uint64_t*)&ctx->Rbx;
    case 4:  return (uint64_t*)&ctx->Rsp;
    case 5:  return (uint64_t*)&ctx->Rbp;
    case 6:  return (uint64_t*)&ctx->Rsi;
    case 7:  return (uint64_t*)&ctx->Rdi;
    case 8:  return (uint64_t*)&ctx->R8;
    case 9:  return (uint64_t*)&ctx->R9;
    case 10: return (uint64_t*)&ctx->R10;
    case 11: return (uint64_t*)&ctx->R11;
    case 12: return (uint64_t*)&ctx->R12;
    case 13: return (uint64_t*)&ctx->R13;
    case 14: return (uint64_t*)&ctx->R14;
    case 15: return (uint64_t*)&ctx->R15;
    default: return NULL;
    }
}

static M128A *ctx_xmm(PCONTEXT ctx, int reg)
{
    switch (reg & 0xF) {
    case 0:  return &ctx->Xmm0;   case 1:  return &ctx->Xmm1;
    case 2:  return &ctx->Xmm2;   case 3:  return &ctx->Xmm3;
    case 4:  return &ctx->Xmm4;   case 5:  return &ctx->Xmm5;
    case 6:  return &ctx->Xmm6;   case 7:  return &ctx->Xmm7;
    case 8:  return &ctx->Xmm8;   case 9:  return &ctx->Xmm9;
    case 10: return &ctx->Xmm10;  case 11: return &ctx->Xmm11;
    case 12: return &ctx->Xmm12;  case 13: return &ctx->Xmm13;
    case 14: return &ctx->Xmm14;  case 15: return &ctx->Xmm15;
    default: return NULL;
    }
}

/* Service an SSE move as a run of 4-byte register accesses.
 *
 * APU registers are 32-bit, so a 16-byte move is four consecutive register
 * accesses rather than one wide one. */
static void apu_sse_read(uint32_t off, uint8_t *dst, int nbytes)
{
    for (int i = 0; i < nbytes; i += 4) {
        uint32_t v = (uint32_t)mcpx_apu_mmio_read(g_apu_state, off + i, 4);
        memcpy(dst + i, &v, 4);
    }
}

static void apu_sse_write(uint32_t off, const uint8_t *src, int nbytes)
{
    for (int i = 0; i < nbytes; i += 4) {
        uint32_t v;
        memcpy(&v, src + i, 4);
        mcpx_apu_mmio_write(g_apu_state, off + i, v, 4);
    }
}

static int decode_modrm_len(const uint8_t *ip, int has_rex_b)
{
    uint8_t modrm = *ip;
    int mod = (modrm >> 6) & 3;
    int rm = (modrm & 7) | (has_rex_b ? 8 : 0);
    int len = 1;

    if (mod == 3) return 1;
    if ((rm & 7) == 4) len += 1; /* SIB */
    if (mod == 0 && (rm & 7) == 5) len += 4; /* disp32 */
    else if (mod == 1) len += 1;
    else if (mod == 2) len += 4;
    return len;
}

/* ============================================================
 * Instruction decoder for APU MMIO access
 * ============================================================ */

static bool apu_decode_and_handle(PCONTEXT ctx, uint32_t mmio_offset, int is_write)
{
    const uint8_t *ip = (const uint8_t *)ctx->Rip;
    if (!g_apu_state) return false;

    int prefix_len = 0;
    int has_66 = 0, has_f2 = 0, has_f3 = 0;
    int rex = 0, has_rex = 0;

    while (1) {
        uint8_t b = ip[prefix_len];
        if (b == 0x66) { has_66 = 1; prefix_len++; }
        else if (b == 0xF2) { has_f2 = 1; prefix_len++; }
        else if (b == 0xF3) { has_f3 = 1; prefix_len++; }
        else if (b >= 0x40 && b <= 0x4F) { rex = b; has_rex = 1; prefix_len++; }
        else break;
    }

    int rex_w = has_rex && (rex & 0x08);
    int rex_r = has_rex && (rex & 0x04);
    int rex_b = has_rex && (rex & 0x01);

    const uint8_t *opcode = ip + prefix_len;
    int access_size = 4;
    if (has_66) access_size = 2;
    if (rex_w) access_size = 8;

    /* SSE / SSE2 128-bit moves.
     *
     * These reach the APU aperture because the recompiled guest code is
     * compiled, not interpreted: MSVC vectorises the generated byte-copy
     * loops (a guest "rep movsd" in sub_001545AC becomes movups), so when a
     * copy runs with a source or destination inside the aperture the faulting
     * instruction is an SSE move rather than a plain mov. The decoder used to
     * reject those and the process died on the unhandled fault.
     *
     *   0F 10 /r  MOVUPS xmm, m128   (F3: MOVSS m32, F2: MOVSD m64, 66: MOVUPD)
     *   0F 11 /r  MOVUPS m128, xmm   (same prefix variants)
     *   0F 28 /r  MOVAPS xmm, m128   (66: MOVAPD)
     *   0F 29 /r  MOVAPS m128, xmm   (66: MOVAPD)
     *   0F 6F /r  MOVDQA/MOVDQU xmm, m128
     *   0F 7F /r  MOVDQA/MOVDQU m128, xmm
     *
     * The scalar forms write only their low 4 or 8 bytes and zero the rest of
     * the destination, which is what the load path below reproduces. */
    if (opcode[0] == 0x0F &&
        (opcode[1] == 0x10 || opcode[1] == 0x11 ||
         opcode[1] == 0x28 || opcode[1] == 0x29 ||
         opcode[1] == 0x6F || opcode[1] == 0x7F)) {
        int is_store = (opcode[1] == 0x11 || opcode[1] == 0x29 || opcode[1] == 0x7F);
        int nbytes = 16;
        if (opcode[1] == 0x10 || opcode[1] == 0x11) {
            if (has_f3) nbytes = 4;        /* MOVSS  */
            else if (has_f2) nbytes = 8;   /* MOVSD  */
        }
        int modrm_len = decode_modrm_len(opcode + 2, rex_b);
        int reg = ((opcode[2] >> 3) & 7) | (rex_r ? 8 : 0);
        M128A *x = ctx_xmm(ctx, reg);
        if (!x) goto apu_decode_unhandled;
        if ((opcode[2] >> 6) == 3) goto apu_decode_unhandled;  /* reg,reg: not MMIO */
        if (is_store) {
            uint8_t buf[16];
            memcpy(buf, x, 16);
            apu_sse_write(mmio_offset, buf, nbytes);
            g_apu_mmio_write_count++;
        } else {
            uint8_t buf[16];
            memset(buf, 0, sizeof buf);   /* scalar forms zero the upper lanes */
            apu_sse_read(mmio_offset, buf, nbytes);
            memcpy(x, buf, 16);
            g_apu_mmio_read_count++;
        }
        g_apu_mmio_sse_count++;
        if (g_apu_mmio_sse_count <= 4 || (g_apu_mmio_sse_count % 100000) == 0) {
            fprintf(stderr, "[APU] SSE %s %d bytes at offset 0x%X (xmm%d), total %d\n",
                    is_store ? "store" : "load",
                    nbytes, mmio_offset, reg, g_apu_mmio_sse_count);
            fflush(stderr);
        }
        ctx->Rip += prefix_len + 2 + modrm_len;
        return true;
    }

    /* MOV r/m, r (write: 88/89) */
    if (opcode[0] == 0x89 || opcode[0] == 0x88) {
        if (opcode[0] == 0x88) access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        int reg = ((opcode[1] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t val = *ctx_reg64(ctx, reg);
        mcpx_apu_mmio_write(g_apu_state, mmio_offset, val, access_size);
        ctx->Rip += prefix_len + 1 + modrm_len;
        g_apu_mmio_write_count++;
        return true;
    }

    /* MOV r/m, imm32 (write: C7 /0) */
    if (opcode[0] == 0xC7) {
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        uint32_t imm = *(uint32_t *)(opcode + 1 + modrm_len);
        mcpx_apu_mmio_write(g_apu_state, mmio_offset, imm, access_size);
        ctx->Rip += prefix_len + 1 + modrm_len + 4;
        g_apu_mmio_write_count++;
        return true;
    }

    /* MOV r/m8, imm8 (write: C6 /0) */
    if (opcode[0] == 0xC6) {
        access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        uint8_t imm = *(opcode + 1 + modrm_len);
        mcpx_apu_mmio_write(g_apu_state, mmio_offset, imm, 1);
        ctx->Rip += prefix_len + 1 + modrm_len + 1;
        g_apu_mmio_write_count++;
        return true;
    }

    /* MOV r, r/m (read: 8A/8B) */
    if (opcode[0] == 0x8B || opcode[0] == 0x8A) {
        if (opcode[0] == 0x8A) access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        int reg = ((opcode[1] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t val = mcpx_apu_mmio_read(g_apu_state, mmio_offset, access_size);
        uint64_t *dst = ctx_reg64(ctx, reg);
        if (access_size == 1) *dst = (*dst & ~0xFFULL) | (val & 0xFF);
        else if (access_size == 2) *dst = (*dst & ~0xFFFFULL) | (val & 0xFFFF);
        else if (access_size == 4) *dst = val & 0xFFFFFFFF;
        else *dst = val;
        ctx->Rip += prefix_len + 1 + modrm_len;
        g_apu_mmio_read_count++;
        return true;
    }

    /* MOVZX r32, r/m8 (0F B6) */
    if (opcode[0] == 0x0F && opcode[1] == 0xB6) {
        access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 2, rex_b);
        int reg = ((opcode[2] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t val = mcpx_apu_mmio_read(g_apu_state, mmio_offset, 1);
        *ctx_reg64(ctx, reg) = val & 0xFF;
        ctx->Rip += prefix_len + 2 + modrm_len;
        g_apu_mmio_read_count++;
        return true;
    }

    /* MOVZX r32, r/m16 (0F B7) */
    if (opcode[0] == 0x0F && opcode[1] == 0xB7) {
        access_size = 2;
        int modrm_len = decode_modrm_len(opcode + 2, rex_b);
        int reg = ((opcode[2] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t val = mcpx_apu_mmio_read(g_apu_state, mmio_offset, 2);
        *ctx_reg64(ctx, reg) = val & 0xFFFF;
        ctx->Rip += prefix_len + 2 + modrm_len;
        g_apu_mmio_read_count++;
        return true;
    }

    /* TEST r/m, r (84/85) - read */
    if (opcode[0] == 0x85 || opcode[0] == 0x84) {
        if (opcode[0] == 0x84) access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        int reg = ((opcode[1] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t mem_val = mcpx_apu_mmio_read(g_apu_state, mmio_offset, access_size);
        uint64_t reg_val = *ctx_reg64(ctx, reg);
        uint64_t result = mem_val & reg_val;
        ctx->EFlags &= ~(0x0001 | 0x0040 | 0x0080 | 0x0800);
        if (result == 0) ctx->EFlags |= 0x0040;
        if (result & (1ULL << (access_size * 8 - 1))) ctx->EFlags |= 0x0080;
        ctx->Rip += prefix_len + 1 + modrm_len;
        g_apu_mmio_read_count++;
        return true;
    }

    /* CMP r/m, r (38/39) */
    if (opcode[0] == 0x39 || opcode[0] == 0x38) {
        if (opcode[0] == 0x38) access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        int reg = ((opcode[1] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t mem_val = mcpx_apu_mmio_read(g_apu_state, mmio_offset, access_size);
        uint64_t reg_val = *ctx_reg64(ctx, reg);
        if (access_size <= 4) {
            mem_val &= (1ULL << (access_size * 8)) - 1;
            reg_val &= (1ULL << (access_size * 8)) - 1;
        }
        uint64_t result = mem_val - reg_val;
        ctx->EFlags &= ~(0x0001 | 0x0040 | 0x0080 | 0x0800);
        if (result == 0) ctx->EFlags |= 0x0040;
        if (mem_val < reg_val) ctx->EFlags |= 0x0001;
        if (result & (1ULL << (access_size * 8 - 1))) ctx->EFlags |= 0x0080;
        ctx->Rip += prefix_len + 1 + modrm_len;
        g_apu_mmio_read_count++;
        return true;
    }

    /* OR r/m, r (08/09) */
    if (opcode[0] == 0x09 || opcode[0] == 0x08) {
        if (opcode[0] == 0x08) access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        int reg = ((opcode[1] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t mem_val = mcpx_apu_mmio_read(g_apu_state, mmio_offset, access_size);
        uint64_t reg_val = *ctx_reg64(ctx, reg);
        mcpx_apu_mmio_write(g_apu_state, mmio_offset, mem_val | reg_val, access_size);
        ctx->Rip += prefix_len + 1 + modrm_len;
        g_apu_mmio_write_count++;
        return true;
    }

    /* AND r/m, r (20/21) */
    if (opcode[0] == 0x21 || opcode[0] == 0x20) {
        if (opcode[0] == 0x20) access_size = 1;
        int modrm_len = decode_modrm_len(opcode + 1, rex_b);
        int reg = ((opcode[1] >> 3) & 7) | (rex_r ? 8 : 0);
        uint64_t mem_val = mcpx_apu_mmio_read(g_apu_state, mmio_offset, access_size);
        uint64_t reg_val = *ctx_reg64(ctx, reg);
        mcpx_apu_mmio_write(g_apu_state, mmio_offset, mem_val & reg_val, access_size);
        ctx->Rip += prefix_len + 1 + modrm_len;
        g_apu_mmio_write_count++;
        return true;
    }

apu_decode_unhandled:
    /* Unrecognized */
    g_apu_mmio_decode_fail++;
    if (g_apu_mmio_decode_fail <= 20) {
        fprintf(stderr, "[APU] MMIO decode fail at RIP=%p offset=0x%X: %02X %02X %02X %02X %02X %02X\n",
                (void*)ctx->Rip, mmio_offset, ip[0], ip[1], ip[2], ip[3], ip[4], ip[5]);
        fflush(stderr);
    }
    return false;
}

/* ============================================================
 * Public API (called from VEH in main.c)
 * ============================================================ */

bool apu_hook_handle_mmio(PCONTEXT ctx, uintptr_t fault_addr,
                          uint32_t fault_xbox_va, int is_write)
{
    uint32_t mmio_offset = fault_xbox_va - APU_MMIO_BASE;
    return apu_decode_and_handle(ctx, mmio_offset, is_write);
}
